export const ROUTES = {
  LANDING_PAGE: "/",
  TRIP_DETAILS: "/TripViewDetails",
  VIEW_PROFILE: "/profileAgency",
  USER_PROFILE: "/profile",
  PROFILE_LEADER: "/leaderProfile",
  LOGIN: "/auth/login",
  VERIFICATION: "/verification",
  BACKLOGIN: "/register",
  PROFILESETUP: "/profilesetup",
  DASHBOARD: "/dashboard",
  USERPROFILE: "/userProfile",
  COMMUNITY_PAGE: "/community",
  TRIP_DETAILS_WITH_ID: (tripId: string) => `/TripViewDetails/${tripId}`,
  VIEW_PACKAGE: "/viewPackage",
};