import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import GlobalLayout from "../components/layout/GlobalLayout";
=======
>>>>>>> origin/feature/community-nearby-essential

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Travio",
  description: "Your ultimate travel companion for planning and managing trips",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> origin/feature/community-nearby-essential
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: {
  children: React.ReactNode;
}) {
=======
}: Readonly<{
  children: React.ReactNode;
}>) {
>>>>>>> origin/feature/community-nearby-essential
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
<<<<<<< HEAD
        style={{ margin: 0, fontFamily: "sans-serif", background: "#000" }}
      >
        <GlobalLayout>{children}</GlobalLayout>
=======
      >
        {children}
>>>>>>> origin/feature/community-nearby-essential
      </body>
    </html>
  );
}
<<<<<<< HEAD

=======
>>>>>>> origin/feature/community-nearby-essential
